---
- gce:
    instance_names: "{{ gce_names }}"
    zone: "{{ gce_zone }}"
    machine_type: "{{ gce_type }}"
    image: "{{ gce_image }}"
    state: "present"
    metadata: '{"sshKeys":"workshop:{{ gce_ssh_key }} workshop"}'
    service_account_email: "{{ gce_account }}"
    credentials_file: "{{ gce_credentials }}"
    project_id: "{{ gce_project }}"
    disk_size: "{{ gce_disksize }}"
    tags: "{{ gce_tags }}"
    disks: "{{gce_disks|default(omit)}}"
  register: gce
- name: Save host data
  add_host:
    hostname: "{{ item.public_ip }}"
    groupname: gce_instances_ips
  with_items: "{{ gce.instance_data }}"
- include: apt.yml
  when: dnsname is defined
- name: Wait for SSH for instances
  wait_for:
    delay: 1
    host: "{{ item.public_ip }}"
    port: 22
    state: started
    timeout: 30
  with_items: "{{ gce.instance_data }}"


